### ISSUE TITLE
Missing libs + wrong path on Ubuntu 12/04

### ISSUE THREAD

**Issue by julienma** [nkadel/rssh-chroot-tools#1]
Hey,
Great script, it saved me a lot of time.

I needed to adapt few things for it to work on Ubuntu 12.04:
- change some paths in `mkchroot.sh`:

```
    FILES="$FILES /usr/lib/openssh/sftp-server"
    FILES="$FILES /usr/lib/rssh/rssh_chroot_helper"
    FILES="$FILES /usr/lib/sftp-server"
```
- manually copy those libs (others were found in /lib/i386-linux-gnu/):

```
    sudo cp /lib/i386-linux-gnu/libnss_compat.so.2 /home/jail/lib/i386-linux-gnu
    sudo cp /lib/i386-linux-gnu/libnsl.so.1 /home/jail/lib/i386-linux-gnu
```

All this seems related to http://askubuntu.com/questions/52617/what-is-usr-lib-i386-linux-gnu-for.
You might want to update your script to take this case into account.

**Comment by nkadel** [comment]
Is one of those "sftp-server" files a symlink? I don't have a Debian system to play with and test on, today. I'd think that only one would be expected.

I do wonder why the those 32-bit files weren't found, and were expected to be used. Which binary has them as dependencies?

**Comment by julienma** [comment]
Yeah, good point, later one is a symlink to the first:

```
~ $ l /usr/lib/openssh/sftp-server
-rwxr-xr-x 1 root root 62K Apr 30  2014 /usr/lib/openssh/sftp-server
~ $ l /usr/lib/sftp-server
lrwxrwxrwx 1 root root 19 Apr 30  2014 /usr/lib/sftp-server -> openssh/sftp-server
```

As for your second question, I hope this can help you:

```
~ $ ldd /lib/i386-linux-gnu/libnss_compat.so.2
    linux-gate.so.1 =>  (0xf77c1000)
    libnsl.so.1 => /lib/i386-linux-gnu/libnsl.so.1 (0xf7797000)
    libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf75ee000)
    /lib/ld-linux.so.2 (0xf77c2000)
~ $ ldd /lib/i386-linux-gnu/libnsl.so.1
    linux-gate.so.1 =>  (0xf76ef000)
    libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf7525000)
    /lib/ld-linux.so.2 (0xf76f0000)
```

I should add that those 2 files are the minimum required I had to add, in addition to your script, otherwise my SCP connection wouldn't work (I use rssh to open an sftp + scp only access).

**Comment by julienma** [comment]
Doing some issue cleaning, so I'm closing this one as it seems stale.
Feel free to open it again if needed.
